=== WallyWest21/Clash-Analysis/Temp/Ressources/FederatorGrammar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Vector				EMPTY>
<!ELEMENT Point					EMPTY>
<!ELEMENT Date					EMPTY>
<!ELEMENT Matrix				(Vector+ , Point)>
<!ELEMENT Product				(Matrix*)>
<!ELEMENT Specification			(Product+)>
<!ELEMENT ClashSpec				(Specification*)>
<!ELEMENT Elements				(LinkToInterference+)>
<!ELEMENT FederatorClashElement (ClashSpec, Elements)>
<!ATTLIST FederatorClashElement Responsible				CDATA		#IMPLIED
								CATDocument				CDATA		#IMPLIED
								Version					(1.0|1.1|1.2)   "1.2">
<!ATTLIST LinkToInterference    Link					CDATA		#REQUIRED
								FirstProductName		CDATA		#IMPLIED
								SecondProductName		CDATA		#IMPLIED
								FirstProductId			CDATA		#IMPLIED
								SecondProductId			CDATA		#IMPLIED
								FirstProductURL			CDATA		#IMPLIED
								SecondProductURL		CDATA		#IMPLIED>
<!ATTLIST Product				Alias					CDATA		#REQUIRED
								ProcessMode				(ENOVIAV5|ENOVIAVPM|STANDALONE) "ENOVIAV5"
								DescriptionID			CDATA		#IMPLIED
								ShapeSource				CDATA		#IMPLIED
								ShapeName				CDATA		#REQUIRED
								Alien					(YES|NO)    "YES">
<!ATTLIST Point					Ux						CDATA		#REQUIRED
								Uy						CDATA		#REQUIRED
								Uz						CDATA		#REQUIRED>
<!ATTLIST Vector				CorrespondingData		(Rx|Ry|Rz)  "Rx"
								Vx						CDATA		#REQUIRED
								Vy						CDATA		#REQUIRED
								Vz						CDATA		#REQUIRED>
<!ATTLIST ClashSpec				Name					CDATA		#REQUIRED
								DistanceClearance		CDATA		#IMPLIED
								TabTitle				CDATA		#REQUIRED
								TabListTitle			CDATA		#REQUIRED
								SelectMode				(INSIDE|OUTSIDE|ALL|TWO_LIST) "ALL"
								CaseOfCalc				(INTERFERE_CONT|INTERFERE_CLEAR|INTERFERE_PENETR_CLASH|INTERFERE_RULE) "INTERFERE_CONT">

=== WallyWest21/Clash-Analysis/Temp/sample.xml.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE FederatorClashElement SYSTEM "Ressources/FederatorGrammar.dtd">
<FederatorClashElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><ClashSpec Name = "Interference.5" TabTitle = "Clash Computation Specification" CaseOfCalc = "INTERFERE_CONT" SelectMode = "INSIDE" TabListTitle = "Products Selected">
<Specification>
<Product Alias = "NAS603-11P (NAS603-11P.1)" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\NAS603-11P.CATPart" DescriptionID = "NAS603-11P.1">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "0.000000" Uy = "0.000000" Uz = "0.000000"/>
</Matrix></Product>
<Product Alias = "9KB412303-00 (BRACKET  [2.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\9KB412303-00.CATPart" DescriptionID = "2LA455740-58.1 --++-- BRACKET  [2.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "-0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "0.000000" Uy = "0.006000" Uz = "-351.586395"/>
</Matrix></Product>
<Product Alias = "B473158-3 (VENEER  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-3.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- VENEER  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<Product Alias = "B473158-5 (HARDWOOD  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-5.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- HARDWOOD  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<Product Alias = "B473158-1 (DOOR PANEL  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-1.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- PANEL ASSY  [1.1] --++-- DOOR PANEL  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<Product Alias = "CDSP5905-06-13 (INSERT, BLIND THD  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\CDSP5905-06-13.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- PANEL ASSY  [1.1] --++-- INSERT, BLIND THD  [1.1]">
<Matrix>
<Vector Vx = "-0.101301" Vy = "0.000000" Vz = "-0.994856" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.994856" Vy = "-0.000000" Vz = "0.101301" CorrespondingData = "Rz"/>
<Point Ux = "-461.984558" Uy = "3422.395996" Uz = "10672.416016"/>
</Matrix></Product>
<Product Alias = "CDSP5905-06-13 (INSERT, BLIND THD  [1.2])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\CDSP5905-06-13.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- PANEL ASSY  [1.1] --++-- INSERT, BLIND THD  [1.2]">
<Matrix>
<Vector Vx = "-0.101301" Vy = "0.000000" Vz = "-0.994856" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.994856" Vy = "-0.000000" Vz = "0.101301" CorrespondingData = "Rz"/>
<Point Ux = "-461.984558" Uy = "3396.996094" Uz = "10672.416016"/>
</Matrix></Product>
<Product Alias = "B473158-7 (DECOR, LAMINATE  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-7.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- DECOR, LAMINATE  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<Product Alias = "B473158-1 (DOOR PANEL  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-1.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- Product1.1 --++-- DOOR PANEL  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<Product Alias = "CDSP5905-06-13 (INSERT, BLIND THD  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\CDSP5905-06-13.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- Product1.1 --++-- INSERT, BLIND THD  [1.1]">
<Matrix>
<Vector Vx = "-0.101301" Vy = "0.000000" Vz = "-0.994856" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.994856" Vy = "-0.000000" Vz = "0.101301" CorrespondingData = "Rz"/>
<Point Ux = "-461.984558" Uy = "3422.395996" Uz = "10672.416016"/>
</Matrix></Product>
<Product Alias = "NAS1149FN632P (WASHER, FLAT, #6  [1.1])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\NAS1149FN632P.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- WASHER, FLAT, #6  [1.1]">
<Matrix>
<Vector Vx = "0.099148" Vy = "0.995073" Vz = "-0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.995073" Vy = "0.099148" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-494.327454" Uy = "3418.029541" Uz = "10680.776367"/>
</Matrix></Product>
<Product Alias = "NAS601-5P (SCREW, PAN HEAD  [1.2])" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\NAS601-5P.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- SCREW, PAN HEAD  [1.2]">
<Matrix>
<Vector Vx = "-1.000000" Vy = "-0.000005" Vz = "-0.000630" CorrespondingData = "Rx"/>
<Vector Vx = "0.000005" Vy = "0.999853" Vz = "-0.017119" CorrespondingData = "Ry"/>
<Vector Vx = "0.000630" Vy = "-0.017119" Vz = "-0.999853" CorrespondingData = "Rz"/>
<Point Ux = "-494.332001" Uy = "3381.570068" Uz = "10680.681641"/>
</Matrix></Product>
<Product Alias = "408.11.550_SUPPORT PLATE (SUPPORT PLATE,  HAFELE SLIDE)" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\408.11.550_SUPPORT PLATE.CATPart" DescriptionID = "B473299-501 --++-- 408.11.550.2 --++-- SUPPORT PLATE,  HAFELE SLIDE">
<Matrix>
<Vector Vx = "0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000005" Vy = "0.000000" Vz = "-1.000000" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000005" CorrespondingData = "Rz"/>
<Point Ux = "-509.470886" Uy = "2937.746094" Uz = "11044.677734"/>
</Matrix></Product>
<Product Alias = "408.11.550_RAIL 22 IN (RAIL 22 IN, HAFELE)" Alien = "YES" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\408.11.550_RAIL 22 IN.CATPart" DescriptionID = "B473299-501 --++-- 408.11.550.2 --++-- RAIL 22 IN, HAFELE">
<Matrix>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000005" Vy = "0.000000" Vz = "-1.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "-0.000005" CorrespondingData = "Rz"/>
<Point Ux = "-428.089264" Uy = "2877.943359" Uz = "11044.677734"/>
</Matrix></Product>
