=== WallyWest21/Clash-Analysis/Temp/Ressources/InterferenceGrammar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Comment				EMPTY>
<!ELEMENT Picture				EMPTY>
<!ELEMENT Vector				EMPTY>
<!ELEMENT Point					EMPTY>
<!ELEMENT Date					EMPTY>
<!ELEMENT ViolatedRule			EMPTY>
<!ELEMENT Matrix				(Vector+ , Point)>
<!ELEMENT Product				(Matrix*)>
<!ELEMENT Viewpoint				(Vector+, Point)>
<!ELEMENT GeometricAspect		(Point*, Viewpoint*)>
<!ELEMENT Interference			(Product+, ViolatedRule*, GeometricAspect, Comment, Picture*)>
<!ELEMENT InterferenceElement	(Date, Interference*)>
<!ATTLIST InterferenceElement	Responsible				CDATA		#IMPLIED
								CATDocument				CDATA		#IMPLIED
								Version					(1.0|1.1|1.2)   "1.2"
								FederatorFather			CDATA		#REQUIRED>
<!ATTLIST Date					Year					CDATA		#REQUIRED
								Month					CDATA		#REQUIRED
								Day						CDATA		#REQUIRED
								Hour					CDATA		#REQUIRED
								Minute					CDATA		#REQUIRED
								Second					CDATA		#REQUIRED>
<!ATTLIST Product				Alias					CDATA		#REQUIRED
								ProcessMode				(ENOVIAV5|ENOVIAVPM|STANDALONE) "ENOVIAV5"
								DescriptionID			CDATA		#IMPLIED
								ShapeSource				CDATA		#IMPLIED
								ShapeName				CDATA		#REQUIRED
								Alien					(YES|NO)    "YES"
								Preview					CDATA		#IMPLIED>
<!ATTLIST Point					Ux						CDATA		#REQUIRED
								Uy						CDATA		#REQUIRED
								Uz						CDATA		#REQUIRED>
<!ATTLIST Vector				CorrespondingData		(Rx|Ry|Rz)  "Rx"
								Vx						CDATA		#REQUIRED
								Vy						CDATA		#REQUIRED
								Vz						CDATA		#REQUIRED>
<!ATTLIST Viewpoint				FocusDistance			CDATA		#REQUIRED
								NearPlane				CDATA		#REQUIRED
								FarPlane				CDATA		#REQUIRED
								ProjectionType			(CYLINDRIC|CONIC) "CYLINDRIC">
<!ATTLIST Picture				HRef					CDATA		#REQUIRED
								Preview					CDATA		#IMPLIED>
<!ATTLIST Comment				Value		 			CDATA		#REQUIRED>
<!ATTLIST GeometricAspect  		IntersectCurveLength 	CDATA		#REQUIRED
								ExtractOrDistValue		CDATA		#REQUIRED>
<!ATTLIST Interference			NumInterf				CDATA		#REQUIRED
								ResultType				(Clash|Contact|Clearance)			"Clash"
								Status					(NotInspected|Relevant|Irrelevant|Solved)	"NotInspected"
								RetrieveInf				(Old|New|Modified)			"New">
<!ATTLIST ViolatedRule			Name					CDATA		#REQUIRED
								TypeCalc				CDATA		#REQUIRED
								Clearance				CDATA		#REQUIRED
								Priority				CDATA		#REQUIRED
								PenetrationCandidate	CDATA		#IMPLIED
								Severity				CDATA		#IMPLIED>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_17.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "17" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "B473158-7 (DECOR, LAMINATE  [1.1])" Preview = "../Picture/28_2_2016_18_22_7_Preview_First_17.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-7.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- DECOR, LAMINATE  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<Product Alias = "B473158-1 (DOOR PANEL  [1.1])" Preview = "../Picture/28_2_2016_18_22_7_Preview_Second_17.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473158-1.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- Product1.1 --++-- DOOR PANEL  [1.1]">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-0.009044" Uy = "0.000000" Uz = "0.002892"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_7_17.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_57.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "Relevant" NumInterf = "57" ResultType = "Clash" RetrieveInf = "New" ResultTypeNoNLS = "Clash"><Comment Value = "Automatic filter : penetration less than "/>
<Product Alias = "79A5552 (79A5552.2)" Preview = "../Picture/28_2_2016_18_22_8_Preview_First_57.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\79A5552.CATPart" DescriptionID = "B473299-501 --++-- B473210-501 --++-- Product1.3 --++-- 79A5552.2">
<Matrix>
<Vector Vx = "-0.979492" Vy = "0.000000" Vz = "0.201483" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.201483" Vy = "-0.000000" Vz = "-0.979492" CorrespondingData = "Rz"/>
<Point Ux = "-408.758698" Uy = "2896.908203" Uz = "11018.072266"/>
</Matrix></Product>
<Product Alias = "NAS514P832-6P (NAS514P832-6P.1.3)" Preview = "../Picture/28_2_2016_18_22_8_Preview_Second_57.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\NAS514P832-6P.CATPart" DescriptionID = "B473299-501 --++-- NAS514P832-6P.1.3">
<Matrix>
<Vector Vx = "0.040906" Vy = "-0.979173" Vz = "0.198862" CorrespondingData = "Rx"/>
<Vector Vx = "0.197287" Vy = "0.203026" Vz = "0.959092" CorrespondingData = "Ry"/>
<Vector Vx = "-0.979492" Vy = "0.000000" Vz = "0.201483" CorrespondingData = "Rz"/>
<Point Ux = "-413.915741" Uy = "2874.429199" Uz = "11008.760742"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "-0.122in" IntersectCurveLength = "1.354in"><Point Ux = "-16.239in" Uy = "113.167in" Uz = "433.404in"/><Point Ux = "-16.12in" Uy = "113.166in" Uz = "433.378in"/></GeometricAspect><Picture HRef = "../Picture/28_2_2016_18_22_8_57.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_66.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "66" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "NAS1149FN632P (NAS1149FN632P.2)" Preview = "../Picture/28_2_2016_18_22_9_Preview_First_66.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\NAS1149FN632P.CATPart" DescriptionID = "B473299-501 --++-- NAS1149FN632P.2">
<Matrix>
<Vector Vx = "0.000000" Vy = "0.026164" Vz = "0.999658" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "-0.999658" Vz = "0.026164" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "-0.000000" CorrespondingData = "Rz"/>
<Point Ux = "-487.493561" Uy = "3028.984131" Uz = "10528.420898"/>
</Matrix></Product>
<Product Alias = "MS21042L06 (MS21042L06.2)" Preview = "../Picture/28_2_2016_18_22_9_Preview_Second_66.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\MS21042L06.CATPart" DescriptionID = "B473299-501 --++-- MS21042L06.2">
<Matrix>
<Vector Vx = "0.000000" Vy = "0.000549" Vz = "1.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "-0.000549" CorrespondingData = "Ry"/>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rz"/>
<Point Ux = "-486.680756" Uy = "3028.984131" Uz = "10528.420898"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_9_66.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_69.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "69" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "B473299-3 (B473299-3.1)" Preview = "../Picture/28_2_2016_18_22_9_Preview_First_69.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\B473299-3.CATPart" DescriptionID = "B473299-501 --++-- B473299-3.1">
<Matrix>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.000000" Vy = "-0.000000" Vz = "-1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-428.889587" Uy = "3279.394043" Uz = "11044.779297"/>
</Matrix></Product>
<Product Alias = "MS24693-S30 (MS24693-S30.2)" Preview = "../Picture/28_2_2016_18_22_9_Preview_Second_69.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\MS24693-S30.CATPart" DescriptionID = "B473299-501 --++-- MS24693-S30.2">
<Matrix>
<Vector Vx = "1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Rz"/>
<Point Ux = "-438.541595" Uy = "3263.519043" Uz = "11039.699219"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_9_69.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_60.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "60" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "408.11.550_RAIL 22 IN (RAIL 22 IN, HAFELE)" Preview = "../Picture/28_2_2016_18_22_8_Preview_First_60.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\408.11.550_RAIL 22 IN.CATPart" DescriptionID = "B473299-501 --++-- B473210-501 --++-- Product1.3 --++-- 408.11.550.1 --++-- RAIL 22 IN, HAFELE">
<Matrix>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000005" Vy = "0.000000" Vz = "-1.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "-0.000005" CorrespondingData = "Rz"/>
<Point Ux = "-428.089264" Uy = "3157.343262" Uz = "11044.677734"/>
</Matrix></Product>
<Product Alias = "408.11.550_PLASTIC CAP (PLASTIC CAP)" Preview = "../Picture/28_2_2016_18_22_8_Preview_Second_60.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\408.11.550_PLASTIC CAP.CATPart" DescriptionID = "B473299-501 --++-- B473210-501 --++-- Product1.3 --++-- 408.11.550.1 --++-- PLASTIC CAP">
<Matrix>
<Vector Vx = "0.000000" Vy = "1.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000005" CorrespondingData = "Ry"/>
<Vector Vx = "0.000005" Vy = "0.000000" Vz = "-1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-445.551758" Uy = "3158.392822" Uz = "11044.510742"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_8_60.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_73.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "Relevant" NumInterf = "73" ResultType = "Clash" RetrieveInf = "New" ResultTypeNoNLS = "Clash"><Comment Value = "Automatic filter : penetration less than "/>
<Product Alias = "TL1150 (TL1150 TOUCH LATCH.1)" Preview = "../Picture/28_2_2016_18_22_9_Preview_First_73.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\TL1150.CATPart" DescriptionID = "B473299-501 --++-- TL1150SMP.1 --++-- TL1150 TOUCH LATCH.1">
<Matrix>
<Vector Vx = "-0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000000" CorrespondingData = "Rz"/>
<Point Ux = "-525.976379" Uy = "3050.820557" Uz = "10528.420898"/>
</Matrix></Product>
<Product Alias = "TL1157 (TL1157.1)" Preview = "../Picture/28_2_2016_18_22_9_Preview_Second_73.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\TL1157.CATPart" DescriptionID = "B473299-501 --++-- TL1150SMP.1 --++-- TL1157.1">
<Matrix>
<Vector Vx = "0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "-0.000000" Vz = "-1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-490.233337" Uy = "3078.514160" Uz = "10534.771484"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "-0.067in" IntersectCurveLength = "1.911in"><Point Ux = "-19.694in" Uy = "119.934in" Uz = "414.506in"/><Point Ux = "-19.628in" Uy = "119.934in" Uz = "414.506in"/></GeometricAspect><Picture HRef = "../Picture/28_2_2016_18_22_9_73.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_38.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "38" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "CDSP5905-08-13 (CDSP5905-08-13.3)" Preview = "../Picture/28_2_2016_18_22_8_Preview_First_38.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\CDSP5905-08-13.CATPart" DescriptionID = "B473299-501 --++-- B473210-501 --++-- B473210-601.1 --++-- CDSP5905-08-13.3">
<Matrix>
<Vector Vx = "-0.204689" Vy = "0.000000" Vz = "-0.978827" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.978827" Vy = "-0.000000" Vz = "0.204689" CorrespondingData = "Rz"/>
<Point Ux = "-410.672791" Uy = "3198.787109" Uz = "11008.086914"/>
</Matrix></Product>
<Product Alias = "NAS514P832-6P (NAS514P832-6P.1)" Preview = "../Picture/28_2_2016_18_22_8_Preview_Second_38.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\NAS514P832-6P.CATPart" DescriptionID = "B473299-501 --++-- NAS514P832-6P.1">
<Matrix>
<Vector Vx = "0.040906" Vy = "-0.979173" Vz = "0.198862" CorrespondingData = "Rx"/>
<Vector Vx = "0.197287" Vy = "0.203026" Vz = "0.959092" CorrespondingData = "Ry"/>
<Vector Vx = "-0.979492" Vy = "0.000000" Vz = "0.201483" CorrespondingData = "Rz"/>
<Point Ux = "-413.915741" Uy = "3198.787109" Uz = "11008.760742"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_8_38.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_76.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\CATIA\Table Set\Users\Al\Dropbox\CATIA\Recycling Stool\Top Assembly.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "26" Hour = "12" Year = "2016" Month = "2" Minute = "45" Second = "7"/><Interference Status = "NotInspected" NumInterf = "76" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "Seat (Part2.1)" Preview = "../Picture/26_2_2016_12_45_11_Preview_First_76.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\CATIA\Table Set\Users\Al\Dropbox\CATIA\Hanging Chair\Part2.CATPart" DescriptionID = "Chair Assy.6 --++-- Part2.1">
<Matrix>
<Vector Vx = "-0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000000" CorrespondingData = "Rz"/>
<Point Ux = "964.682007" Uy = "46.109509" Uz = "378.459991"/>
</Matrix></Product>
<Product Alias = "Front Leg (Part3.1)" Preview = "../Picture/26_2_2016_12_45_11_Preview_Second_76.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\CATIA\Table Set\Users\Al\Dropbox\CATIA\Hanging Chair\Part3.CATPart" DescriptionID = "Chair Assy.6 --++-- Part3.1">
<Matrix>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rz"/>
<Point Ux = "1368.541992" Uy = "44.839508" Uz = "0.000000"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/26_2_2016_12_45_11_76.png"/></Interference></InterferenceElement>
