=== WallyWest21/Clash-Analysis/Temp/Ressources/InterferenceGrammar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Comment				EMPTY>
<!ELEMENT Picture				EMPTY>
<!ELEMENT Vector				EMPTY>
<!ELEMENT Point					EMPTY>
<!ELEMENT Date					EMPTY>
<!ELEMENT ViolatedRule			EMPTY>
<!ELEMENT Matrix				(Vector+ , Point)>
<!ELEMENT Product				(Matrix*)>
<!ELEMENT Viewpoint				(Vector+, Point)>
<!ELEMENT GeometricAspect		(Point*, Viewpoint*)>
<!ELEMENT Interference			(Product+, ViolatedRule*, GeometricAspect, Comment, Picture*)>
<!ELEMENT InterferenceElement	(Date, Interference*)>
<!ATTLIST InterferenceElement	Responsible				CDATA		#IMPLIED
								CATDocument				CDATA		#IMPLIED
								Version					(1.0|1.1|1.2)   "1.2"
								FederatorFather			CDATA		#REQUIRED>
<!ATTLIST Date					Year					CDATA		#REQUIRED
								Month					CDATA		#REQUIRED
								Day						CDATA		#REQUIRED
								Hour					CDATA		#REQUIRED
								Minute					CDATA		#REQUIRED
								Second					CDATA		#REQUIRED>
<!ATTLIST Product				Alias					CDATA		#REQUIRED
								ProcessMode				(ENOVIAV5|ENOVIAVPM|STANDALONE) "ENOVIAV5"
								DescriptionID			CDATA		#IMPLIED
								ShapeSource				CDATA		#IMPLIED
								ShapeName				CDATA		#REQUIRED
								Alien					(YES|NO)    "YES"
								Preview					CDATA		#IMPLIED>
<!ATTLIST Point					Ux						CDATA		#REQUIRED
								Uy						CDATA		#REQUIRED
								Uz						CDATA		#REQUIRED>
<!ATTLIST Vector				CorrespondingData		(Rx|Ry|Rz)  "Rx"
								Vx						CDATA		#REQUIRED
								Vy						CDATA		#REQUIRED
								Vz						CDATA		#REQUIRED>
<!ATTLIST Viewpoint				FocusDistance			CDATA		#REQUIRED
								NearPlane				CDATA		#REQUIRED
								FarPlane				CDATA		#REQUIRED
								ProjectionType			(CYLINDRIC|CONIC) "CYLINDRIC">
<!ATTLIST Picture				HRef					CDATA		#REQUIRED
								Preview					CDATA		#IMPLIED>
<!ATTLIST Comment				Value		 			CDATA		#REQUIRED>
<!ATTLIST GeometricAspect  		IntersectCurveLength 	CDATA		#REQUIRED
								ExtractOrDistValue		CDATA		#REQUIRED>
<!ATTLIST Interference			NumInterf				CDATA		#REQUIRED
								ResultType				(Clash|Contact|Clearance)			"Clash"
								Status					(NotInspected|Relevant|Irrelevant|Solved)	"NotInspected"
								RetrieveInf				(Old|New|Modified)			"New">
<!ATTLIST ViolatedRule			Name					CDATA		#REQUIRED
								TypeCalc				CDATA		#REQUIRED
								Clearance				CDATA		#REQUIRED
								Priority				CDATA		#REQUIRED
								PenetrationCandidate	CDATA		#IMPLIED
								Severity				CDATA		#IMPLIED>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_14.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "Relevant" NumInterf = "14" ResultType = "Clash" RetrieveInf = "New" ResultTypeNoNLS = "Clash"><Comment Value = "Automatic filter : penetration less than "/>
<Product Alias = "CDSP5905-06-13 (INSERT, BLIND THD  [1.1])" Preview = "../Picture/28_2_2016_18_22_7_Preview_First_14.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\CDSP5905-06-13.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- PANEL ASSY  [1.1] --++-- INSERT, BLIND THD  [1.1]">
<Matrix>
<Vector Vx = "-0.101301" Vy = "0.000000" Vz = "-0.994856" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.994856" Vy = "-0.000000" Vz = "0.101301" CorrespondingData = "Rz"/>
<Point Ux = "-461.984558" Uy = "3422.395996" Uz = "10672.416016"/>
</Matrix></Product>
<Product Alias = "CDSP5905-06-13 (INSERT, BLIND THD  [1.1])" Preview = "../Picture/28_2_2016_18_22_7_Preview_Second_14.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\CDSP5905-06-13.CATPart" DescriptionID = "DOOR INSTALLATION, UPPER GALLEY --++-- DOOR ASSY  [1.1] --++-- Product1.1 --++-- INSERT, BLIND THD  [1.1]">
<Matrix>
<Vector Vx = "-0.101301" Vy = "0.000000" Vz = "-0.994856" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "-0.994856" Vy = "-0.000000" Vz = "0.101301" CorrespondingData = "Rz"/>
<Point Ux = "-461.984558" Uy = "3422.395996" Uz = "10672.416016"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "-0.405in" IntersectCurveLength = "0in"><Point Ux = "-17.986in" Uy = "134.74in" Uz = "420.153in"/><Point Ux = "-18.389in" Uy = "134.74in" Uz = "420.194in"/></GeometricAspect><Picture HRef = "../Picture/28_2_2016_18_22_7_14.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_72.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "72" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "TL1156 (TL1156)" Preview = "../Picture/28_2_2016_18_22_9_Preview_First_72.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\TL1156.CATPart" DescriptionID = "B473299-501 --++-- TL1150SMP.1 --++-- TL1156">
<Matrix>
<Vector Vx = "-0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000000" CorrespondingData = "Rz"/>
<Point Ux = "-535.746399" Uy = "3063.520508" Uz = "10518.260742"/>
</Matrix></Product>
<Product Alias = "TL1150 (TL1150 TOUCH LATCH.1)" Preview = "../Picture/28_2_2016_18_22_9_Preview_Second_72.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\TL1150.CATPart" DescriptionID = "B473299-501 --++-- TL1150SMP.1 --++-- TL1150 TOUCH LATCH.1">
<Matrix>
<Vector Vx = "-0.000000" Vy = "0.000000" Vz = "1.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000000" CorrespondingData = "Rz"/>
<Point Ux = "-525.976379" Uy = "3050.820557" Uz = "10528.420898"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_9_72.png"/></Interference></InterferenceElement>

=== WallyWest21/Clash-Analysis/Temp/DataBase/sample.xml_21.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../Ressources/UnifiedStyleSheet_EN.xsl"?>
<!DOCTYPE InterferenceElement SYSTEM "../Ressources/InterferenceGrammar.dtd">
<InterferenceElement Version = "1.2" CATDocument = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\Product85.CATProduct" Responsible = "Al" FederatorFather = "..\sample.xml.xml"><Date Day = "28" Hour = "18" Year = "2016" Month = "2" Minute = "22" Second = "6"/><Interference Status = "NotInspected" NumInterf = "21" ResultType = "Contact" RetrieveInf = "New" ResultTypeNoNLS = "Contact"><Comment Value = ""/>
<Product Alias = "408.11.550_SUPPORT PLATE (SUPPORT PLATE,  HAFELE SLIDE)" Preview = "../Picture/28_2_2016_18_22_7_Preview_First_21.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\408.11.550_SUPPORT PLATE.CATPart" DescriptionID = "B473299-501 --++-- 408.11.550.2 --++-- SUPPORT PLATE,  HAFELE SLIDE">
<Matrix>
<Vector Vx = "0.000000" Vy = "-1.000000" Vz = "-0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "0.000005" Vy = "0.000000" Vz = "-1.000000" CorrespondingData = "Ry"/>
<Vector Vx = "1.000000" Vy = "-0.000000" Vz = "0.000005" CorrespondingData = "Rz"/>
<Point Ux = "-509.470886" Uy = "2937.746094" Uz = "11044.677734"/>
</Matrix></Product>
<Product Alias = "175H710-180 (175H710-180.2)" Preview = "../Picture/28_2_2016_18_22_7_Preview_Second_21.png" ShapeName = "Shape 1" ProcessMode = "STANDALONE" ShapeSource = "C:\Users\Al\Dropbox\ESS\The Comparator\Nouveau dossier (2)\175H710-180.CATPart" DescriptionID = "B473299-501 --++-- B473210-501 --++-- Product1.3 --++-- 175H710-180.2">
<Matrix>
<Vector Vx = "0.000000" Vy = "-1.000000" Vz = "0.000000" CorrespondingData = "Rx"/>
<Vector Vx = "-1.000000" Vy = "0.000000" Vz = "-0.000005" CorrespondingData = "Ry"/>
<Vector Vx = "0.000005" Vy = "0.000000" Vz = "-1.000000" CorrespondingData = "Rz"/>
<Point Ux = "-469.901947" Uy = "2896.908203" Uz = "11032.886719"/>
</Matrix></Product>
<GeometricAspect ExtractOrDistValue = "0 mm" IntersectCurveLength = "0 mm"/><Picture HRef = "../Picture/28_2_2016_18_22_7_21.png"/></Interference></InterferenceElement>
